### ISSUE TITLE
Download does not work

### ISSUE THREAD

**Issue by RimGu** [isanchop/stuhack#10]
Top right Download button is inactive and gives an error in Chrome extensions

 up_buttons[0].parentNode.parentNode.insertBefore(button_cv, up_buttons[0].parentNode.parentElement.children[3]);

**Comment by isanchop** [comment]
#9 Check this out
It depends in which version of Studocu web version you are getting you either have to use the previous version ([v0.4.3](https://github.com/isanchop/stuhack/releases/tag/v0.4.3)) or the latest.

**Comment by RimGu** [comment]
Using 0.4.3 did the trick! Thanks!
