### ISSUE TITLE
Cannot download PDF file

### ISSUE THREAD

**Issue by papimatthews34** [isanchop/stuhack#13]
Hello I cannot download PDF file, it opens on a separate window which allows me to view the document but when i hit print, I cannot scale to full page PDF.

**Comment by isanchop** [comment]
I do not understand your problem. The problem is you can not save it as pdf? or you can not make it full size, so you have big margins?

**Comment by Cheskaz** [comment]
Not sure if this is the same as the problem I was having, but if it's a long document, you may have to scroll all the way down before hitting download. Studocu was only loading the first 10 pages which meant that the extension could only grab the first 10 pages. (Sorry if this isn't actually at all helpful)
