### ISSUE TITLE
Error can't use extension

### ISSUE THREAD

**Issue by limyuxuan2** [isanchop/stuhack#14]
Hi i got an error and the extension is greyed out

Uncaught TypeError: Cannot read properties of undefined (reading 'parentNode')

Stack Trace
version-check.js:13 (anonymous function)

This line was highlighted in chrome:
 up_buttons[0].parentNode.parentNode.insertBefore(button_cv, up_buttons[0].parentNode.parentElement.children[3]);

Stack Trace
remove-banner.js:10 (anonymous function)

This line was also highlighted:
premiumButton.parentNode.removeChild(premiumButton);

**Comment by isanchop** [comment]
#9 Check this out
It depends in which version of Studocu web version you are getting you either have to use the previous version ([v0.4.3](https://github.com/isanchop/stuhack/releases/tag/v0.4.3)) or the latest.
