### ISSUE TITLE
Download Content blocked out  

### ISSUE THREAD

**Issue by 0oBlueberryo0** [isanchop/stuhack#19]
Hey, 
I downloaded the latest version, installed it in Chrome and unfortunately it doesn't work. (In print menu only headings no content visible). 
I have read through the old discussions and examined the code after the adjustments and could not find any error. 
So I tried the add-on while I was logged in and even if not.
Is there any other source of error I could investigate or is the site more up to date than the add-on? 

Thank you very much for your effort!
![Screenshot](https://user-images.githubusercontent.com/122025625/210782519-bc9688bd-e144-4c5f-ab3d-e80b03deba14.JPG)

**Comment by isanchop** [comment]
Heey did you press the download button??
Seems like you are trying to print straight from their website and then you get the content blocked.
Once you hit the download button a new chrome tab should appear with the content you want to download. :)

**Comment by 0oBlueberryo0** [comment]
thanks so much for your fast reply! 
the problem was that the window in the browser was not maximized and therefore the buttons were displayed differently. 
saved a students life again, thanks!
