### ISSUE TITLE
Does this work on Kiwi browser (Android)?

### ISSUE THREAD

**Issue by Digital-XxX** [isanchop/stuhack#21]
Is there a way for this to work on android?

**Comment by isanchop** [comment]
It should work!
Just follow the same steps as for google chrome:

1) Git clone or download file and unzip on a folder 
2) Go to the extensions tab on google chrome (chrome://extensions/)
3) Enable "Developer mode" on the top right of the tab
4) Press on "Load unpacked" new feature that appeared on top left corner
5) Browse the path you downloaded the extension and choose select
6) Enjoy :)

**Comment by Digital-XxX** [comment]
> It should work! Just follow the same steps as for google chrome:
> 
> 1. Git clone or download file and unzip on a folder
> 2. Go to the extensions tab on google chrome (chrome://extensions/)
> 3. Enable "Developer mode" on the top right of the tab
> 4. Press on "Load unpacked" new feature that appeared on top left corner
> 5. Browse the path you downloaded the extension and choose select
> 6. Enjoy :)

I already did that and followed the method on how to download documents but it's not downloading the file.

**Comment by isanchop** [comment]
Hey!! 
Try the new [version](https://github.com/isanchop/stuhack/releases/tag/v0.5.0), it should work in any device and resolution.
Hope this fixes your problem :)

**Comment by Digital-XxX** [comment]
> Hey!! Try the new [version](https://github.com/isanchop/stuhack/releases/tag/v0.5.0), it should work in any device and resolution. Hope this fixes your problem :)

It works now. Thanks.
