### ISSUE TITLE
Documents with longer than 20 pages are unable to load completely for downloading

### ISSUE THREAD

**Issue by RiRiRiley** [isanchop/stuhack#22]
Chrome on Win 10 Version 109.0.5414.75 (Official Build) (64-bit)

**Comment by isanchop** [comment]
As stated on the instructions to download, you must scroll through the entire document before hitting the download button if the document is longer than 20 pages.

**Comment by RiRiRiley** [comment]
Thanks for your reply, but once the doc wouldn't load beyond 20 pages with stuhack enabled.

**Comment by isanchop** [comment]
I have been trying to find your issue, but it just works fine for me.
Was it only on one documentary or several?
Have you tried another device?
Could you provide the documents that don't load?
Thanks :)

**Comment by SafEight** [comment]
I've found that when logged in on studocu and with this extension active, only the first 20 pages load. In an incognito window, the entire document is loaded.

**Comment by samuu0** [comment]
i have the same problem

**Comment by RiRiRiley** [comment]
https://www.studocu.com/en-us/document/university-of-kentucky/federal-criminal-law/criminal-law-outline-ch-1-4/14339048

This was the file that I tried, and I've been getting this error message. "Uncaught TypeError: Cannot read properties of undefined (reading 'parentNode')."

Second to what SafEight said, the extension works in incognito mode.

**Comment by TakataMasayoshi** [comment]
I have the same problem on Mac OS with Chrome.

**Comment by TokyoFingers** [comment]
After switching to Window 11 I'm no longer able to download documents of any length. The page will open to the preview document tab, but once I select 'save' the browser will freeze. 

The error reads:
**Errors**
Uncaught TypeError: Cannot read properties of undefined (reading 'childNodes')

**Context**
https://www.studocu.com/en-ca/document/langara-college/self-and-others-i-awareness/n1130-week-7-spirituality-introduction-to-spiritual-health/35601245

**Stack Trace**
remove-banner.js:9 (anonymous function)
This is highlighted -->	var premiumButton = document.getElementById('header-position-handle').childNodes[0].childNodes[1].childNodes[0].childNodes[1];

Is there anything I need to edit in the code or under 'inspect' when I download documents?
Thank you.

**Comment by isanchop** [comment]
@TokyoFingers @RiRiRiley That error should no longer appear on new version [v0.5.1](https://github.com/isanchop/stuhack/releases/tag/v0.5.1)

**Comment by TokyoFingers** [comment]
@isanchop 
Wow, you work fast! Thank you for the update :)

I tried reloading the webpage, reinstalling, and shutting downing my computer earlier but it didn't work.  I didn't have issues on  my iPad though.

Thanks again!
