### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kkwnn** [isanchop/stuhack#31]
After I downloaded the extension on chrome, how do I use it to download the documents? I still have the premium blocks on my web. I can't click on the chrome extension on the document viewing page.

**Comment by isanchop** [comment]
Have you installed on chrome following the instructions on the readme?

**Comment by kkwnn** [comment]
Yup! I downloaded the file and unpacked it on google chrome extension tab as instructed. I can see the extension working but the documents are just still blocked :(

**Comment by isanchop** [comment]
Which domain are you in one of this two domains (https://www.studocu.com or https://www.studeersnel.nl) and if so do you get this header?
<img width="1269" alt="image" src="https://github.com/isanchop/stuhack/assets/67743899/cfcc55bb-49ad-4c63-bbf0-74f761e0cf84">

**Comment by kkwnn** [comment]
Oh! It works now when I expand the tab full screen, nvm then lmao THANK YOU SO MUCH!! :)
