### ISSUE TITLE
Print to PDF is not working properly

### ISSUE THREAD

**Issue by chririnaldi** [isanchop/stuhack#34]
While the preview of the document to be downloaded is displayed correctly in the new tab, printing to PDF does not render correctly.
One image plus one quarter of the next image are printed on the same page.
Eliminating the margins and increasing the scale to 120% gives an acceptable result.

**Comment by isanchop** [comment]
Hey, thanks for the feedback. Is it specific to a particular document or applicable to all documents? Have you tried the settings mentioned in this issue (#33)?

**Comment by nolnolisnolnol** [comment]
this is also my problem this is my example file (context: the "this is a preview" part goes with the printed version, hope you could fix this advance thanks)

**Comment by nolnolisnolnol** [comment]
this is still a problem actually cause i also still experience this (context: the "this is a preview" part goes with the printed version) hope this would fix advance thanks this is the example file 
[chapter-06-tb-answer-key_compress.pdf](https://github.com/isanchop/stuhack/files/13060344/chapter-06-tb-answer-key_compress.pdf)

**Comment by nolnolisnolnol** [comment]
this is still a problem actually cause i also still experience this (context: the "this is a preview" part goes with the printed version) hope this would fix advance thanks this is the example file 
[Badminton Assessment key for students pgy.pdf](https://github.com/isanchop/stuhack/files/13060350/Badminton.Assessment.key.for.students.pgy.pdf)

**Comment by hisaetbyeol** [comment]
hi! idk if this will helps but what ive been doing is manually removing 'this is preview document' with the dev tools like this:

![image](https://github.com/isanchop/stuhack/assets/97919585/80e73b85-245d-431d-8638-5c46f434efcd)

**Comment by isanchop** [comment]
New update [v0.5.4](https://github.com/isanchop/stuhack/tree/v0.5.4) should be working 
Thanks to @Pradeep1409  :)
