### ISSUE TITLE
Premium banners don't get removed on new version of studocu

### ISSUE THREAD

**Issue by Sepulchie** [isanchop/stuhack#4]
Premium banners stay at the top of the page and parts of the page stay blurred, extension gives an error  
"Cannot read properties of null (reading 'childNodes')" in removebanner.js line 2

**Comment by isanchop** [comment]
It does work.
Did you update to version 0.3.5?

**Comment by Sepulchie** [comment]
![782256e39696b6f6ee809f552f856694](https://user-images.githubusercontent.com/46627397/148983879-9e556743-55fc-43ae-9baa-308cbf3fee55.png)
This is the version I have installed right now
![197fc7946f4b7c98e7e474c913b92d33](https://user-images.githubusercontent.com/46627397/148983919-5aec3ce2-0690-4744-b3b1-f683d9778657.png)
This is the topmost error
Is there something I should be doing differently?

**Comment by isanchop** [comment]
Try updating again, the error should not apear any longer, but any other way the extension is working fine.
I just checked the document you are trying to see and I have no problem at all.
Do you have your browser up to date?
Thanks for feedback :)
