### ISSUE TITLE
Documents are blurred

### ISSUE THREAD

**Issue by Sofiiasra** [isanchop/stuhack#40]
I cant see them anymore

**Comment by Filtar2000** [comment]
same

**Comment by Filtar2000** [comment]
blur pass not working

**Comment by nolnolisnolnol** [comment]
yeh same problem here

**Comment by daniellecruz2048** [comment]
same

**Comment by isanchop** [comment]
try the new version [v0.5.5](https://github.com/isanchop/stuhack/releases/tag/v0.5.5) ;)
