### ISSUE TITLE
[Fix] Blur and AD Message #39 #40 #41

### ISSUE THREAD

**Issue by Chapoly1305** [isanchop/stuhack#42]
Fix for issue #39 #40 #41

To exchange the idea and for enlighten the discussion, I purpose a potential way to resolve this issue. I have no intention to infringe any rules. The blur effect is base on monitoring the CSS of page-content, in this way any change to the page-content style will lead to a overwrite to the style. However, there is no monitor of the sub-div. You may run the code in console to validate the effectiveness. 

**Before** 

<img width="1075" alt="image" src="https://github.com/isanchop/stuhack/assets/25316415/11ce126c-13ee-48b3-83cb-c18c472b6475">

**After** 

<img width="1066" alt="image" src="https://github.com/isanchop/stuhack/assets/25316415/97b8caf0-7845-4c66-8594-68f4f31113b7">

**If the document has multiple pages, remember to scroll all the way down before execute the code. Otherwise, due to the pages are loaded when you read them, the script will not be able to remove blur before it's loaded from server.** 
 

``` JavaScript
// Remove Blur
const blurNodes = document.querySelectorAll('.page-content');
for (let i = 0; i < blurNodes.length; i++) {
  if (blurNodes[i].hasChildNodes() && blurNodes[i].style["filter"] != "") {
    console.log("[Info] Processing Page", i+1, "...")
    myDiv = blurNodes[i].firstChild;
    if (myDiv.firstChild.nodeName == 'IMG') {
      console.log("[Failed] Page", i+1, "is an image.")
    } else {
      blurNodes[i].parentNode.append(myDiv);
      blurNodes[i].removeChild(blurNodes[i].firstChild);
      console.log("[Success] Removed Blur on Page", i)
    }
  }
}

// Remove Notices
const bannerNodesA = document.querySelectorAll('.banner-wrapper');
for (let i = 0; i < bannerNodesA.length; i++) {
    bannerNodesA[i].parentNode.removeChild(bannerNodesA[i]);
}

const bannerNodesB = document.querySelectorAll('._60e676a00207');
for (let i = 0; i < bannerNodesB.length; i++) {
    bannerNodesB[i].parentNode.removeChild(bannerNodesB[i]);
}

const blurNotice = document.querySelectorAll('._869f7c361ca9');
for (let i = 0; i < blurNotice.length; i++) {
    blurNotice[i].parentNode.removeChild(blurNotice[i]);
}

```

**Comment by Jugones3** [comment]
The code does not seem to be working for me. When I input it into the console, it gives back an error. Maybe I am doing it wrong, I don't know.

![Captura](https://github.com/isanchop/stuhack/assets/150349645/201e4b88-b526-4b00-8298-2cb733766130)

**Comment by Ivak124** [comment]
yea same thing happens to me when i put it in. I asked chatgpt and she said that ad block or certain blockers may be stopping it. Did that and it came with this instead "undefined" ---> after refreshing page to see if it had worked and blur was gone ----> 
index.js:58    GET https://connect.facebook.net/en_US/fbevents.js net::ERR_CONNECTION_REFUSED
(anonymous) @ index.js:58
y.run @ browser.js:153
d @ browser.js:123
setTimeout (async)
c @ browser.js:41
o.nextTick @ browser.js:143
YoZL.t.exports @ index.js:55
e.load @ protos.js:261
d.initialize @ index.js:107
initialize @ protos.js:322
(anonymous) @ index.ts:166
(anonymous) @ tslib.es6.js:103
(anonymous) @ tslib.es6.js:108
u @ tslib.es6.js:73
Promise.then (async)
a @ tslib.es6.js:76
(anonymous) @ tslib.es6.js:76
s @ tslib.es6.js:72
n.load @ ajs-destination.bundle.0f003b5e4b03680982b4.js:1
(anonymous) @ event-queue.js:35
(anonymous) @ tslib.es6.js:103
(anonymous) @ tslib.es6.js:108
(anonymous) @ tslib.es6.js:80
s @ tslib.es6.js:72
n.register @ event-queue.js:30
(anonymous) @ index.ts:405
(anonymous) @ index.ts:403
(anonymous) @ tslib.es6.js:103
(anonymous) @ tslib.es6.js:108
(anonymous) @ tslib.es6.js:80
s @ tslib.es6.js:72
n.register @ index.ts:399
(anonymous) @ analytics.min.js:1
(anonymous) @ tslib.es6.js:103
(anonymous) @ tslib.es6.js:108
u @ tslib.es6.js:73
Promise.then (async)
a @ tslib.es6.js:76
u @ tslib.es6.js:73
Promise.then (async)
a @ tslib.es6.js:76
u @ tslib.es6.js:73
Promise.then (async)
a @ tslib.es6.js:76
u @ tslib.es6.js:73
Promise.then (async)
a @ tslib.es6.js:76
(anonymous) @ tslib.es6.js:76
s @ tslib.es6.js:72
Wt @ index.ts:187
(anonymous) @ index.ts:337
(anonymous) @ tslib.es6.js:103
(anonymous) @ tslib.es6.js:108
u @ tslib.es6.js:73
Promise.then (async)
a @ tslib.es6.js:76
(anonymous) @ tslib.es6.js:76
s @ tslib.es6.js:72
Zt @ index.ts:305
(anonymous) @ index.ts:385
Promise.then (async)
(anonymous) @ index.ts:386
t @ index.ts:182
n @ index.ts:384
n.load @ index.ts:436
n.standalone @ index.ts:440
(anonymous) @ standalone-analytics.ts:64
(anonymous) @ tslib.es6.js:103
(anonymous) @ tslib.es6.js:108
(anonymous) @ tslib.es6.js:80
s @ tslib.es6.js:72
Yt @ standalone-analytics.ts:60
(anonymous) @ standalone.ts:68
(anonymous) @ tslib.es6.js:103
(anonymous) @ tslib.es6.js:108
(anonymous) @ tslib.es6.js:80
s @ tslib.es6.js:72
ee @ analytics.min.js:1
(anonymous) @ analytics.min.js:1
(anonymous) @ analytics.min.js:1
(anonymous) @ analytics.min.js:1
DevTools failed to load source map: Could not load content for wasm://wasm/false: Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by Chapoly1305** [comment]
@Ivak124  @Jugones3  
Do you mind to share the URL you accessed? So I could double check on the page source code.

**Comment by az13096** [comment]
@Chapoly1305 
It also doesn't work for me. I used it here: https://www.studocu.com/en-ca/document/the-university-of-western-ontario/zombie-apocalypse/history-2186b-final-exam-notes/437889 

![chrome_uviRqTING7](https://github.com/isanchop/stuhack/assets/150412054/d0cf8b89-9ec3-4269-a5fe-cb76b3977316)

**Comment by nolnolisnolnol** [comment]
> yea same thing happens to me when i put it in. I asked chatgpt and she said that ad block or certain blockers may be stopping it. Did that and it came with this instead "undefined" ---> after refreshing page to see if it had worked and blur was gone ----> index.js:58 GET https://connect.facebook.net/en_US/fbevents.js net::ERR_CONNECTION_REFUSED (anonymous) @ index.js:58 y.run @ browser.js:153 d @ browser.js:123 setTimeout (async) c @ browser.js:41 o.nextTick @ browser.js:143 YoZL.t.exports @ index.js:55 e.load @ protos.js:261 d.initialize @ index.js:107 initialize @ protos.js:322 (anonymous) @ index.ts:166 (anonymous) @ tslib.es6.js:103 (anonymous) @ tslib.es6.js:108 u @ tslib.es6.js:73 Promise.then (async) a @ tslib.es6.js:76 (anonymous) @ tslib.es6.js:76 s @ tslib.es6.js:72 n.load @ ajs-destination.bundle.0f003b5e4b03680982b4.js:1 (anonymous) @ event-queue.js:35 (anonymous) @ tslib.es6.js:103 (anonymous) @ tslib.es6.js:108 (anonymous) @ tslib.es6.js:80 s @ tslib.es6.js:72 n.register @ event-queue.js:30 (anonymous) @ index.ts:405 (anonymous) @ index.ts:403 (anonymous) @ tslib.es6.js:103 (anonymous) @ tslib.es6.js:108 (anonymous) @ tslib.es6.js:80 s @ tslib.es6.js:72 n.register @ index.ts:399 (anonymous) @ analytics.min.js:1 (anonymous) @ tslib.es6.js:103 (anonymous) @ tslib.es6.js:108 u @ tslib.es6.js:73 Promise.then (async) a @ tslib.es6.js:76 u @ tslib.es6.js:73 Promise.then (async) a @ tslib.es6.js:76 u @ tslib.es6.js:73 Promise.then (async) a @ tslib.es6.js:76 u @ tslib.es6.js:73 Promise.then (async) a @ tslib.es6.js:76 (anonymous) @ tslib.es6.js:76 s @ tslib.es6.js:72 Wt @ index.ts:187 (anonymous) @ index.ts:337 (anonymous) @ tslib.es6.js:103 (anonymous) @ tslib.es6.js:108 u @ tslib.es6.js:73 Promise.then (async) a @ tslib.es6.js:76 (anonymous) @ tslib.es6.js:76 s @ tslib.es6.js:72 Zt @ index.ts:305 (anonymous) @ index.ts:385 Promise.then (async) (anonymous) @ index.ts:386 t @ index.ts:182 n @ index.ts:384 n.load @ index.ts:436 n.standalone @ index.ts:440 (anonymous) @ standalone-analytics.ts:64 (anonymous) @ tslib.es6.js:103 (anonymous) @ tslib.es6.js:108 (anonymous) @ tslib.es6.js:80 s @ tslib.es6.js:72 Yt @ standalone-analytics.ts:60 (anonymous) @ standalone.ts:68 (anonymous) @ tslib.es6.js:103 (anonymous) @ tslib.es6.js:108 (anonymous) @ tslib.es6.js:80 s @ tslib.es6.js:72 ee @ analytics.min.js:1 (anonymous) @ analytics.min.js:1 (anonymous) @ analytics.min.js:1 (anonymous) @ analytics.min.js:1 DevTools failed to load source map: Could not load content for wasm://wasm/false: Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

could you elaborate this? make a video solution?

**Comment by Chapoly1305** [comment]
> @Chapoly1305 It also doesn't work for me. I used it here: https://www.studocu.com/en-ca/document/the-university-of-western-ontario/zombie-apocalypse/history-2186b-final-exam-notes/437889
> 
> ![chrome_uviRqTING7](https://user-images.githubusercontent.com/150412054/281952733-d0cf8b89-9ec3-4269-a5fe-cb76b3977316.png)

The blur on this example case cannot be removed. 
From the web source code, the page 3 and  similar pages are blur images instead of blur effect on web page. Since the server did not sent actual content, then it cannot be removed with the code I posted.

**Comment by Chapoly1305** [comment]
> > yea same thing happens to me when i put it in. I asked chatgpt and she said that ad block or certain blockers may be stopping it. Did that and it came with this instead "undefined" ---> after refreshing page to see if it had worked and blur was gone ----> index.js:58 GET https://connect.facebook.net/en_US/fbevents.js net::ERR_CONNECTION_REFUSED (anonymous) @ index.js:58 y.run @ browser.js:153 d @ browser.js:123 setTimeout (async) c @ browser.js:41 o.nextTick @ browser.js:143 YoZL.t.exports @ index.js:55 e.load @ protos.js:261 d.initialize @ index.js:107 initialize @ protos.js:322 (anonymous) @ index.ts:166 (anonymous) @ tslib.es6.js:103 (anonymous) @ tslib.es6.js:108 u @ tslib.es6.js:73 Promise.then (async) a @ tslib.es6.js:76 (anonymous) @ tslib.es6.js:76 s @ tslib.es6.js:72 n.load @ ajs-destination.bundle.0f003b5e4b03680982b4.js:1 (anonymous) @ event-queue.js:35 (anonymous) @ tslib.es6.js:103 (anonymous) @ tslib.es6.js:108 (anonymous) @ tslib.es6.js:80 s @ tslib.es6.js:72 n.register @ event-queue.js:30 (anonymous) @ index.ts:405 (anonymous) @ index.ts:403 (anonymous) @ tslib.es6.js:103 (anonymous) @ tslib.es6.js:108 (anonymous) @ tslib.es6.js:80 s @ tslib.es6.js:72 n.register @ index.ts:399 (anonymous) @ analytics.min.js:1 (anonymous) @ tslib.es6.js:103 (anonymous) @ tslib.es6.js:108 u @ tslib.es6.js:73 Promise.then (async) a @ tslib.es6.js:76 u @ tslib.es6.js:73 Promise.then (async) a @ tslib.es6.js:76 u @ tslib.es6.js:73 Promise.then (async) a @ tslib.es6.js:76 u @ tslib.es6.js:73 Promise.then (async) a @ tslib.es6.js:76 (anonymous) @ tslib.es6.js:76 s @ tslib.es6.js:72 Wt @ index.ts:187 (anonymous) @ index.ts:337 (anonymous) @ tslib.es6.js:103 (anonymous) @ tslib.es6.js:108 u @ tslib.es6.js:73 Promise.then (async) a @ tslib.es6.js:76 (anonymous) @ tslib.es6.js:76 s @ tslib.es6.js:72 Zt @ index.ts:305 (anonymous) @ index.ts:385 Promise.then (async) (anonymous) @ index.ts:386 t @ index.ts:182 n @ index.ts:384 n.load @ index.ts:436 n.standalone @ index.ts:440 (anonymous) @ standalone-analytics.ts:64 (anonymous) @ tslib.es6.js:103 (anonymous) @ tslib.es6.js:108 (anonymous) @ tslib.es6.js:80 s @ tslib.es6.js:72 Yt @ standalone-analytics.ts:60 (anonymous) @ standalone.ts:68 (anonymous) @ tslib.es6.js:103 (anonymous) @ tslib.es6.js:108 (anonymous) @ tslib.es6.js:80 s @ tslib.es6.js:72 ee @ analytics.min.js:1 (anonymous) @ analytics.min.js:1 (anonymous) @ analytics.min.js:1 (anonymous) @ analytics.min.js:1 DevTools failed to load source map: Could not load content for wasm://wasm/false: Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
> 
> could you elaborate this? make a video solution?

This is irrelevant to the blur issue. It seems to be a connection issue, sometime refreash the page could resolve.

**Comment by Peerkzy** [comment]
> > @Chapoly1305 It also doesn't work for me. I used it here: https://www.studocu.com/en-ca/document/the-university-of-western-ontario/zombie-apocalypse/history-2186b-final-exam-notes/437889
> > ![chrome_uviRqTING7](https://user-images.githubusercontent.com/150412054/281952733-d0cf8b89-9ec3-4269-a5fe-cb76b3977316.png)
> 
> The blur on this example case cannot be removed. From the web source code, the page 3 and similar pages are blur images instead of blur effect on web page. Since the server did not sent actual content, then it cannot be removed with the code I posted.

is there any way to fix the issue when it is an image?

**Comment by nolnolisnolnol** [comment]
so there is no solution for this? it seems studocu update itself

**Comment by Chapoly1305** [comment]
> so there is no solution for this? it seems studocu update itself

Yes, unfortunately in the case a picture is used instead of blurring effect, there is no way to remove it at this moment.

**Comment by Pradeep1409** [comment]
I'm working hard to solve this quickly because of an upcoming exam. Unfortunately, the exam has been postponed 🤣.

**Comment by Ivak124** [comment]
![Uploading Screen Shot 2023-11-22 at 5.04.08 pm.png…]()

**Comment by Ivak124** [comment]
Ok so when I go to download from stuhack which takes it to a different tab just the document, the blurred pages before are now minimised (so before it was blurry, after downloading, those same pages have just become minimised, shrunk to about 1/8 of the page - is there perhaps some code to enlarge it back to its original size???)

**Comment by landoncrabtree** [comment]
The blurred images are stored on Cloudfront with a URL like 
`https://d3tvd1u91rr79.cloudfront.net/a2aa9a4720ce8e5692f963a70e3cfcc9/html/pages/blurred/page15.webp...`

Simply removing `/blurred/` from the URL will get you the unblurred image. I wrote a quick Python script to do this for me, here:

```python
import requests
from PIL import Image
from io import BytesIO

images = []
page_length = 44

for i in range(1, page_length + 1):
    url = f"https://d3tvd1u91rr79.cloudfront.net/a2aa9a4720ce8e5692f963a70e3cfcc9/html/pages/page{i}.webp?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6XC9cL2QzdHZkMXU5MXJyNzkuY2xvdWRmcm9udC5uZXRcL2EyYWE5YTQ3MjBjZThlNTY5MmY5NjNhNzBlM2NmY2M5XC9odG1sXC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzAwNzU0NDA5fX19XX0_&Signature=Tm36W~ftvySp7r5myMj4XRnNhp9fz~vPsQo6Z9m157UCFbHF~4HExTzr9qltQMpijIxr-FrdM5BibtL69a-B-D0EEgwgIlsjD7fiovqz9-yWJ4Y2qWT6C-dd2UHfmNU42pmbsY6zvihhXveFkmOa1gRERtf5Au5b0vSBnGr4ZQZc~WGPwGgnVjo~OIFep8FZjz10fvk4kQiIfLtbhGkECN9UTHlnJiv3DJGkwfPMHlFXY7VPoJyRi0yT1kPI7EHEJk5OHbnvSbYdquyyqS7yCxA7JmE-kXkBu~Zu-Ia9CgKww0eECunoJ7tM6ewJt6ihj5QrXbmptiEAQJwRKSBXIQ__&Key-Pair-Id=APKAJ535ZH3ZAIIOADHQ"
    # download the file
    r = requests.get(url, allow_redirects=True)
    images.append(Image.open(BytesIO(r.content)))
    print(f"Downloaded page {i} of {page_length}")

images[0].save('down.pdf', save_all=True, append_images=images[1:])
```

I'm sure this can be replicated in Javascript and added to the extension, too.

**Comment by landoncrabtree** [comment]
> > so there is no solution for this? it seems studocu update itself
> 
> No. Unfortunately in the case a picture is used instead of blurring effect, there is no way to remove it at this moment.

https://github.com/isanchop/stuhack/issues/46

**Comment by isanchop** [comment]
try the new version [v0.5.5](https://github.com/isanchop/stuhack/releases/tag/v0.5.5) 
Should be fixed now :P

**Comment by Chapoly1305** [comment]
It worked absolutely like a charm!!! You are awesome my dude! @isanchop
