### ISSUE TITLE
Bad print Pdf 

### ISSUE THREAD

**Issue by Jemingita** [isanchop/stuhack#44]
Hi, sometimes ago i notice that all pdf i try to downlod present some imperfection like: word trasparent or part of html from the original document (like the Premium Banner ) inside the pdf. How i can fix that?
I would also say this tool is very useful, so good job guys @isanchop @Pradeep1409

**Comment by Pradeep1409** [comment]
I'm working hard to solve this quickly because of an upcoming exam. Unfortunately, the exam has been postponed 🤣

**Comment by IUseArchBTW-Debian** [comment]
i just manually use F12 and select the banner delete the `<div>` one up the heirarchy, but now they added in blurred pages. The unblured versions are stored somewhere in their servers that checks for your account status.
