### ISSUE TITLE
Some pages got blurred

### ISSUE THREAD

**Issue by itssybit** [isanchop/stuhack#45]
Hi, when i open a document some pages got blurred, can you fix that please? thanks!

**Comment by Ivak124** [comment]
i get this too. Even if this doesn't get fixed, seriously just want to thank the developers for this tool. Really helped me this sem, and grateful for what it did.

**Comment by landoncrabtree** [comment]
See here https://github.com/isanchop/stuhack/issues/42#issuecomment-1823331212

**Comment by isanchop** [comment]
try the new version [v0.5.5](https://github.com/isanchop/stuhack/releases/tag/v0.5.5) ;)
