### ISSUE TITLE
Manifest Unreadable Error

### ISSUE THREAD

**Issue by addy1256** [isanchop/stuhack#47]
I installed the extension with the zip file following the instructions in the readme.md
`1) Git clone or download file and unzip on a folder 
2) Go to the extensions tab on google chrome (chrome://extensions/)
3) Enable "Developer mode" on the top right of the tab
4) Press on "Load unpacked" new feature that appeared on top left corner
5) Browse the path you downloaded the extension and choose select
6) Enjoy :)`

After clicking developer mode and clicking 'Load unpack' i got this error message,
> Failed to load extension
File
~\Downloads\stuhack
Error
Manifest file is missing or unreadable
Could not load manifest`

I've tried deleting and redownloading the zip file but to no avail, any idea what could be happening?

**Comment by zN3utr4l** [comment]
you need to unzip the package and upload the stuhack v0.5.3 folder

**Comment by addy1256** [comment]
> you need to unzip the package and upload the stuhack v0.5.3 folder

@zN3utr4l is the stuhack v0.5.3 folder different from the zipped package? otherwise i've done exactly that but i still get the manifest error

**Comment by isanchop** [comment]
It is!
Read the instructions on [here](https://github.com/isanchop/stuhack/blob/main/README.md)
Hope you got it solved :)
