### ISSUE TITLE
Does this mean that i have successfully installed it? 

### ISSUE THREAD

**Issue by notduckiee** [isanchop/stuhack#48]
does this mean that i have successfully installed it? if so, how can i download the whole file without having to download each picture? 

![image](https://github.com/isanchop/stuhack/assets/143173021/a08fc0b4-35d7-4978-b4c1-394a662772ce)

**Comment by zN3utr4l** [comment]
Yes, you can also check in: chrome://extensions/
![image](https://github.com/isanchop/stuhack/assets/73225008/5dc23c24-003d-40d6-8549-e50964fcf81b)

**Comment by isanchop** [comment]
Yess that's our logo!
Welcome 🤗
