### ISSUE TITLE
Large "preview banner" being printed on some pages

### ISSUE THREAD

**Issue by GoBig-Or-GoHome** [isanchop/stuhack#49]
Seems like Studocu has figured out how to place a large banner when printing files to PDF. 

Fortunately the notes are still visible on the web, but the PDF will have a large banner on some (but not all) of the pages. I have attached a 3-page document as an example. The banner is on pg. 3. 

A larger document it starts at pg. 3 and then shows up on alternating pages. 
[Procedural Fairness.pdf](https://github.com/isanchop/stuhack/files/13537768/Procedural.Fairness.pdf)

**Comment by leezaj** [comment]
A temporary fix while this gets fixed (using Chromium):

- After clicking download, right click anywhere and click Inspect
- Right click all the div class that have "banner-wrapper" in them and click Hide Element
- Do this for all banners
- Once done, you can print and save to PDF

**Comment by leezaj** [comment]
A temporary fix that worked for me while this gets fixed (using Chromium):

    After clicking download, right click anywhere and click Inspect
    Right click all the div class that have "banner-wrapper" in them and click Hide Element
    Do this for all banners
    Once done, you can print and save to PDF

**Comment by leezaj** [comment]
A fix that worked for me while this gets resolved (using Chromium):

- After clicking download, right click anywhere and click Inspect
- Right click all the div class that have "banner-wrapper" in them and click Hide Element
- Do this for all banners
- Once done, you can print and save to PDF

**Comment by zN3utr4l** [comment]
@leezaj,
It doesn't work, for me some pages are small, blurred images.
![image](https://github.com/isanchop/stuhack/assets/73225008/1bb1523b-6814-42f3-99ef-697a173fe645)

**Comment by isanchop** [comment]
New update [v0.5.4](https://github.com/isanchop/stuhack/tree/v0.5.4) should be working 
Thanks to @Pradeep1409  :)
