### ISSUE TITLE
the extension doesn't work

### ISSUE THREAD

**Issue by yoyoy74662000** [isanchop/stuhack#5]
-Premium banner remove (works)
-Blur pass (works)
-Documents download (how does it work?)

**Comment by yoyoy74662000** [comment]
i just found out that you have to sign in first.

**Comment by yoyoy74662000** [comment]
I couldn't download with ctrl+p
![image](https://user-images.githubusercontent.com/26075572/150657164-b38edca0-87eb-416f-b4d9-a42c432ff82e.png)

**Comment by yoyoy74662000** [comment]
I couldn't download with ctrl+p
![image](https://user-images.githubusercontent.com/26075572/150657164-b38edca0-87eb-416f-b4d9-a42c432ff82e.png)

**Comment by yoyoy74662000** [comment]
I just read the code. Thanks.

![image](https://user-images.githubusercontent.com/26075572/150657322-38418356-56e7-4e6b-80f0-92afcc5f8e52.png)

**Comment by isanchop** [comment]
There is a readme file with the step by step about how to download a document.
I hope it helps you 😄
