### ISSUE TITLE
Blurred images fix doesn't work

### ISSUE THREAD

**Issue by MarcoBuda** [isanchop/stuhack#51]
Hi, I downloaded the last version (v0.5.5) but the blurred images fix isn't working for me

**Comment by PabloSoage** [comment]
Same for me

**Comment by alexisgagnon** [comment]
Same here :)

**Comment by dominik7680** [comment]
Same here :C

**Comment by isanchop** [comment]
Could you provide the link to the document not working?

**Comment by marcoaurelian** [comment]
Same, it seems there are some documents where it cannot bypass the blur on all the pages. For me the blur appears every other page, so it works 50/50

**Comment by isanchop** [comment]
It was working only in some screen resolutions,
try the new version [v0.5.6](https://github.com/isanchop/stuhack/releases/tag/v0.5.6) and tell me if it is working now :)

**Comment by marcoaurelian** [comment]
Found a solution with v0.5.5! You can right click the document in chrome and "open in reading mode" will make it work and unlock all pages of the document.

**Comment by marcoaurelian** [comment]
And the v0.5.6 works perfectly. Thank you man for creating this, you're a G!

**Comment by isanchop** [comment]
Nice!

**Comment by alexisgagnon** [comment]
Works perfectly, thanks a lot !

**Comment by Duynguyen239** [comment]
The v0.5.6 blurred content fix doesn't work properly. I have trouble in using PrintPreview to download documents from Studocu
