### ISSUE TITLE
Doesn't download...

### ISSUE THREAD

**Issue by Andrewsapo** [isanchop/stuhack#6]
Good morning, first of all thanks for your work! However i have a problem. When i'm on studocu and i click to "download" it redirects me on the website that ask me to have a Premium Account. Why? Thanks!

**Comment by isanchop** [comment]
Hello Andrew ;)
Check out the [readme file ](https://github.com/isanchop/stuhack/blob/main/README.md)
I wrote there how you can download any document.
Hope you find it helpful!
Thanks for your support!

**Comment by isanchop** [comment]
Anyway I was working on that but left this project behind. Maybe I will update it some time soon.

**Comment by Andrewsapo** [comment]
Thanks a lot, i was wrong the passages!

**Comment by isanchop** [comment]
Just updated, now you can just press the download button to get the document preview and download. 
The triple click has been disabled and will no longer be useful :)
