### ISSUE TITLE
Request to make it work on Dutch website/domain "studeersnel.nl" as well

### ISSUE THREAD

**Issue by Quentinos01** [isanchop/stuhack#7]
I absolutely love it! Would it be possible to make it work on different domains as well?  For example, in the Netherlands its called studeersnel.nl instead of studocu.com because its originally a Dutch website (:

**Comment by isanchop** [comment]
Yes!
It is super easy fix, just add on the manifest.json file the domain/s you want to use the chrome extension.
So your manifest file should look something like this:
```
{
  "manifest_version": 2,
 
  "name": "StuHack",
  "version": "0.4.2",
  "description": "Banner remover, filter pass & document downloader",
  "icons": { 
    "16": "img/icon16.png",
    "48": "img/icon48.png",
    "128": "img/icon128.png" },
 
  "content_scripts": [{
    "js": ["version-check.js", "remove-banner.js", "remove-blur.js", "doc-viewer.js"],
    "css": ["style.css"],
    "matches": ["https://www.studocu.com/*", "https://www.studeersnel.nl/*"]
  }]
}
```
Thanks for your suport ;)

**Comment by Quentinos01** [comment]
thanks! it works. maybe something for the next update so it will work for others as well (;

also noticed that only the download button is in spanish

**Comment by isanchop** [comment]
Done :P
